name: RunPython
on: push
jobs:
    pyset:
        runs-on: ubuntu-latest

        steps:
        - name: makecheckout
          uses: actions/checkout@4
        - name: setpython
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: runfile
          run: python myfirst.py