name: SendEmail
on: push
jobs:
    email:
        runs-on: ubuntu-latest

        steps:
        - name: Send email
          uses: hilarion5/send-mail@v1.0.2
          with:
            host: smtp.google.com
            port: 465
            account: ${{secrets.ACCOUNT}}
            password: ${{secrets.MAIL_PASSWORD}}
            sender: hilarion5 
            from: ${{secrets.MAIL_ADDRESS}}
            to: abishekdeepakff@gmail.com
            subject: mail title.
            body: your messages.
            contentType: text/plain
            attachments: '[{"path":"README.md"}]'